# Generated by Django 4.0.6 on 2022-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('SC', 'SMALL COW'), ('BC', 'BIG COW'), ('NB', 'NEW BORN')], max_length=2)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CowVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('expiration_date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
