# Generated by Django 4.0.6 on 2022-07-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CowVaccine',
            new_name='Medicine',
        ),
    ]
