# Generated by Django 4.0.6 on 2022-07-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0002_rename_cowvaccine_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=1),
        ),
    ]
