# Generated by Django 4.0.6 on 2022-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0005_cow_milkaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(default='cowMedicine.jpg', upload_to='cowMeicines/'),
        ),
    ]
