# Generated by Django 4.0.6 on 2022-07-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0006_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
