# Generated by Django 4.0.6 on 2022-07-28 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0007_milk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(auto_now_add=True)),
                ('milking', models.FloatField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cows.cow')),
            ],
        ),
    ]
