# Generated by Django 4.0.6 on 2022-07-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cows', '0009_alter_cowinfo_today'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cowinfo',
            options={'ordering': ('-today',)},
        ),
    ]
