# Generated by Django 4.0.6 on 2022-07-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_stocks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='image',
            field=models.ImageField(default='Stockdefault.jpg', upload_to='stockImages/'),
        ),
    ]
