# Generated by Django 4.0.6 on 2022-07-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_alter_stocks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontdisplayImg', models.ImageField(default='defaultDisplay.jpg', upload_to='display_img/')),
                ('cowDisplay', models.ImageField(default='cowDisplay.jpg', upload_to='cowImage/')),
                ('goatDisplay', models.ImageField(default='goatDefault.jpg', upload_to='goatImage/')),
            ],
        ),
    ]
