# Generated by Django 4.0.6 on 2022-07-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_displayimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displayimage',
            name='cowDisplay',
            field=models.ImageField(blank=True, default='cowDisplay.jpg', null=True, upload_to='cowImage/'),
        ),
        migrations.AlterField(
            model_name='displayimage',
            name='frontdisplayImg',
            field=models.ImageField(blank=True, default='defaultDisplay.jpg', null=True, upload_to='display_img/'),
        ),
        migrations.AlterField(
            model_name='displayimage',
            name='goatDisplay',
            field=models.ImageField(blank=True, default='goatDefault.jpg', null=True, upload_to='goatImage/'),
        ),
    ]
