# Generated by Django 4.0.6 on 2022-07-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0005_alter_displayimage_cowdisplay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('C', 'COW'), ('G', 'GOAT'), ('O', 'OTHERS')], max_length=1)),
                ('date', models.DateField()),
            ],
        ),
    ]
