# Generated by Django 4.0.6 on 2022-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='image',
            field=models.ImageField(default='goatdefault.jpg', upload_to='GoatImages/'),
        ),
    ]
